version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: "monday"
      time: "06:00"
      timezone: "Europe/Istanbul"
    assignees:
      - "@evrentan"
    reviewers:
      - "@evrentan"
    labels:
      - "dependency"
    commit-message:
      prefix: "chore(npm dependency updates):"
